In [1]:
import tensorflow as tf
hello =  tf.constant('hello tf!')
sess = tf.Session()
print(sess.run(hello))




E:\anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


b'hello tf!'


In [3]:
import cv2
print('hello opencv')

hello opencv


In [11]:
import cv2
img = cv2.imread('N:/tensflow/picturedeal/th.jpg',1) #read image 参数一图片名参数二0为灰度图1为彩色图
cv2.imshow('image',img)  #参数一窗口名称参数二当前图片内容
cv2.waitKey(0)

-1

In [13]:
import cv2
img = cv2.imread('N:/tensflow/picturedeal/th.jpg',1)
cv2.imwrite('image1.jpg',img)

True

In [20]:
import cv2
img = cv2.imread('N:/tensflow/picturedeal/th.jpg',1)
cv2.imwrite('imagetest.jpg',img,[cv2.IMWRITE_JPEG_QUALITY,50])
#1M 100k 10k 0-100 有损压缩


True

In [21]:
import cv2
img = cv2.imread('N:/tensflow/picturedeal/th.jpg',1)
cv2.imwrite('imagetest.png',img,[cv2.IMWRITE_PNG_COMPRESSION,0])
#jpg 值越大压缩比越小   png值越小压缩比越小

True

In [2]:
import cv2
img = cv2.imread('N:/tensflow/picturedeal/tim.jpg',1)
(b,g,r) = img[50,50]
print(b,g,r)
for i in range(1,100):
    img[10+i,100] = (255,0,0)
cv2.imshow('image',img)
cv2.waitKey(0)





81 68 178


-1

In [7]:
import tensorflow as tf
data1 = tf.constant(2.5)
data2 = tf.Variable(10,name='var')
print(data1)
print(data2)
'''
sess = tf.Session()
print(sess.run(data1))
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(data2))

#本质 tf = tensor + 计算图
# tensor 数据
#op
#graphs 数据操作图
#session
'''
init = tf.global_variables_initializer()
sess = tf.Session()
with sess:
    sess.run(init)
    print(sess.run(data2))





Tensor("Const_4:0", shape=(), dtype=float32)
<tf.Variable 'var_4:0' shape=() dtype=int32_ref>
10


In [3]:
import tensorflow as tf
data1 = tf.constant(6)
data2 = tf.constant(2)
dataAdd = tf.add(data1,data2)
dataMul = tf.multiply(data1,data2)
dataSub = tf.subtract(data1,data2)
dataDiv = tf.divide(data1,data2)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    print(sess.run(init))
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
print('end!')    






None
8
12
4
3.0
end!


In [5]:
import tensorflow as tf
data1 = tf.constant(6)
data2 = tf.Variable(2)
dataAdd = tf.add(data1,data2)
dataCopy = tf.assign(data2,dataAdd)#dataAdd ->data2
dataMul = tf.multiply(data1,data2)
dataSub = tf.subtract(data1,data2)
dataDiv = tf.divide(data1,data2)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(dataAdd))
    print(sess.run(dataMul))
    print(sess.run(dataSub))
    print(sess.run(dataDiv))
    print('sess.run(dataCopy)',sess.run(dataCopy))
    print('dataCopy.eval()',dataCopy.eval())
    print('tf.get_default_session()',tf.get_default_session().run(dataCopy))
    
print('end!')    





8
12
4
3.0
sess.run(dataCopy) 8
dataCopy.eval() 14
tf.get_default_session() 20
end!


In [7]:
#placehold

import tensorflow as tf
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1,data2)
with tf.Session() as sess:
    print(sess.run(dataAdd,feed_dict = {data1:6,data2:2}))
    #1 dataAdd 2 data (feed_dict = {1:6,2:2})
print('end!')    



8.0
end!


In [12]:
#类比 数组 M行N列【】 内部【】 【里面 列数据】 【】中括号整体 行数
#[[6.6]] [[6,6]]
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],[2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],[3,4],[5,6]])
print(data4.shape)#维度
with tf.Session() as sess:
    print(sess.run(data4))     #打印整体
    print(sess.run(data4[0]))  #
    print(sess.run(data4[:,0]))
    print(sess.run(data4[0,0]))





(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1


In [15]:
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],[2]])
data3 = tf.constant([[3,3]])
data4 = tf.constant([[1,2],[3,4],[5,6]])
matMul = tf.matmul(data1,data2)
matMul2 = tf.multiply(data1,data2)
matAdd = tf.add(data1,data3)
with tf.Session() as sess:
    print(sess.run(matMul)) #矩阵相乘 
    print(sess.run(matAdd)) #矩阵相加
    print(sess.run(matMul2))#行列互乘
    print(sess.run([matMul2,matAdd]))
    

[[24]]
[[9 9]]
[[12 12]
 [12 12]]
[array([[12, 12],
       [12, 12]]), array([[9, 9]])]
